project:
  type: website
website:
  title: "Connor Wessel"
  site-url: https://www.clwessel.github.io/website
  description: "Website of Connor Wessel"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: cv.qmd
        text: CV
      - href: blog.qmd
        text: Blog
    tools: 
      - icon: envelope
        href: clwessel@proton.me
      - icon: github
        href: https://github.com/clwessel
      - icon: linkedin
        href: https://www.linkedin.com/in/connor-l-wessel/
  page-footer: 
    left: "Last updated: October 2026" 
    right:
      - text: Made using Quarto
        href: https://quarto.org/
  back-to-top-navigation: true
  reader-mode: false
  repo-url: https://github.com/clwessel/website
  repo-actions: [source]
  open-graph: true
code-fold: show
code-tools: false
code-annotations: hover
code-block-border-left: true
code-line-numbers: true
syntax-highlighting: atom-one
respect-user-color-scheme: true
lightbox: true
format: 
    html:
        theme:
          light: [flatly]
          dark: [darkly]
        css: style.css
        toc: true
        toc-title: "Sections"
        other-links: false
        link-external-icon: true
        link-external-newwindow: true
execute:
    warning: false

