project:
  type: website
website:
  title: "Connor Wessel"
  site-url: https://clwessel.github.io
  description: "Website of Connor Wessel"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: cv.qmd
        text: CV
      - href: blog.qmd
        text: Blog
    tools: 
      - icon: envelope
        href: clwessel@proton.me
        text: Email
      - icon: github
        href: https://github.com/clwessel
        text: Github
      - icon: linkedin
        href: https://www.linkedin.com/in/connor-l-wessel/
        text: Linkedin
      - icon: code-slash
        href: https://github.com/clwessel/clwessel.github.io
        text: Source code
  page-footer: 
    left: "Last updated: October 2026" 
    right:
      - text: Made using Quarto
        href: https://quarto.org/
  back-to-top-navigation: true
  reader-mode: false
  repo-url: https://github.com/clwessel/clwessel.github.io
  repo-actions: [source]
  open-graph: true
code-block-border-left: true
code-line-numbers: true
syntax-highlighting: atom-one
format: 
    html:
        theme:
          light: [flatly]
          dark: [darkly]
        css: style.css
        toc: true
        toc-title: "Sections"
        other-links: false
        link-external-icon: true
        link-external-newwindow: true
        respect-user-color-scheme: true
        lightbox: true
        code-fold: show
        code-tools: false
        code-annotations: hover
execute:
    warning: false
    freeze: true

